### PR TITLE
#3 - added support for MySQL

### PR DESCRIPTION
**Pull request by mariodavid**
Attached you'll find scripts for MySQL init scripts.

For more RDBMS, you can take a look at a file, I created for the runtime-diagnose app-component which tells you how to start all RDBMS supported from studio via docker:
https://github.com/mariodavid/cuba-component-runtime-diagnose/blob/master/create-databases.md

### CODE REVIEW

**Comment by pfurini** [comment]
Thanks for this @mariodavid ! I'll merge it ASAP, as soon as I have some spare time to publish the new version on bintray.

**Comment by pfurini** [comment]
Hi, I'm closing this because I created the scripts, alongside all the other RDBMS versions, using automated docker containers, and I forgot to merge this before the other commits.. nonetheless I added a mention in the README ;)  Thanks!

**Comment by mariodavid** [comment]
Can you share the script? Thats sounds great...

**Comment by pfurini** [comment]
Unfortunately the "automation" is not so automated, sorry ;) the process that builds the DB script is not exposed to gradle, but it's a Studio feature, and the missing Mysql and Oracle drivers complicates the matter.

So for now I only included small `start` and `stop` gradle tasks, that calls into bash scripts that in turn starts and stops docker containers for the various RDBMS. You can find them in `extra.gradle`.
I created a custom docker image `nexbit/mssql-server-linux` on docker hub (forked from another guy, but that was too old to use), because the original  image does not support an init script (and I use it for creating the DB), and for Mysql I opted for mariadb 10 (that's what I use in other projects).
But apart from these small tweaks, it is not so much different from what you already do in your repos...

Bye!

**Pull request closed without merging**
